name: Build example app

on:
  push:
    branches:
      - tabris-js-action

jobs:
  build_android:
    name: Build example app for Android platform
    runs-on: ubuntu-latest
    steps:
      - uses: eclipsesource/tabris-js-action@master
        with:
          tabris-build-key: ${{ secrets.TABRIS_BUILD_KEY }}
          path: .example
