name: Build example app

on: [push]

jobs:
  build_ios:
    name: Build iOS example app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update Node.js
        run: |
          sudo npm install -g n
          sudo n latest
      - name: Install tabris-cli
        run: sudo npm install -g tabris-cli
      - name: Build Tabris app in ".example"
        env:
          TABRIS_BUILD_KEY: ${{ secrets.TABRIS_BUILD_KEY }}
        run: |
          cd .example
          sudo -E tabris build ios
          tree -d build/cordova/platforms/ios/build
      - name: Archive build ios .app
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ios-example-app
          path: .example/build/cordova/platforms/ios/build/emulator/Tabris.js\ Maps\ Plugin\ Example.app
